version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"